# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 784feeabb2e31a534c9e4d7ead8fd475cddef5dc3f8106c2be1b61fc7dc3bb300618cbed1056879a47e021c5aa3eb29f18d49435ffd52ef395f268968d47a0d6

test:
  secret_key_base: d21edfe9d52bf3b6ddeb24c796181aa8e73ac35f5ee45fa2f277c8b7826fa690b0af0f03fd7837066705d662bb19651b799e57c49c6f8717a0b8d4621351fd5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
